### ISSUE TITLE
Asus ux430uar error on install

### ISSUE THREAD

**Issue by programrty** [dominiksalvet/gitpack#7] opened 2020-04-14 09:54 UTC
Hello.
Notebook - Asus ux430uar
OS opensuse tumbleweed
installing asus fan control I get an error

```
#/files/GIT/gitpack/src/gitpack install https://github.com/dominiksalvet/asus-fan-control
fatal: Invalid object name refs/remote/HEAD
<ERROR> install https://github.com/dominiksalvet/asus-fan-control

```
/files/GIT/gitpack/src/gitpack - directory where gitpсk is installed locally

Please, help

**Comment by dominiksalvet** [comment] 2020-04-14 13:05
BTW, I have moved this issue to GitPack as it looks like to be more GitPack-related.

**Comment by programrty** [comment] 2020-04-16 08:24
Hello
> Please, do not rush - let us examine one issue at time (now your OP issue). Please, provide full GitPack log, which you can find in the `/var/log/gitpack/gitpack.log` file and maybe we can come up with something... 💡

```
/files/GIT/gitpack # src/gitpack install github.com/dominiksalvet/gitpack
fatal: Invalid object name refs/remote/HEAD
<ERROR> install github.com/dominiksalvet/gitpack
```

gitpack.log

```
2020-04-16 10:20:25 [log] src/gitpack install github.com/dominiksalvet/gitpack
2020-04-16 10:20:25 [db] /var/lib/gitpack/status
2020-04-16 10:20:25 [install] github.com/dominiksalvet/gitpack
2020-04-16 10:20:25 [url] github.com/dominiksalvet/gitpack
2020-04-16 10:20:25 [repo] github.com/dominiksalvet/gitpack /var/cache/gitpack/repo/github.com/dominiksalvet/gitpack/
2020-04-16 10:20:27 [get] github.com/dominiksalvet/gitpack /var/lib/gitpack/status
2020-04-16 10:20:27 [exit] 128
```

**Comment by dominiksalvet** [comment] 2020-04-16 14:55
Ok, thanks. :ok_hand:

1. What is the output of `git config --list` on your system?
2. Please run GitPack with `clean`, e.g. `src/gitpack clean` and check whether the issue persists.
3. If so, go to GitPack cache directory (global - */var/cache/gitpack*, local - *~/.cache/gitpack*) and find your desired Git repository (e.g., */var/cache/gitpack/repo/github.com/dominiksalvet/gitpack/.git*) and once you are in this directory, run `tree refs/` and report the output. Please install `tree` if you do not have it, or provide the *refs/* directory structure another way.
4. To have a complete idea of GitPack's execution, please provide the output of the command with tracing enabled by running `sh -x <command>`. E.g., `sh -x src/gitpack install github.com/dominiksalvet/gitpack`.

These steps will definitely point us towards the core of this issue.

**Comment by dominiksalvet** [comment] 2020-04-19 16:19
BTW, what is your Git version (`git --version`)? :thinking:

**Comment by arthas168** [comment] 2020-09-15 04:28
Hello @dominiksalvet ! :wave: I'm having the same issue... Doesn't seem like this convo is resolved

**Comment by dominiksalvet** [comment] 2020-09-15 09:36
@arthas168 Please answer the same questions as @programrty – GitPack log, questions from https://github.com/dominiksalvet/gitpack/issues/7#issuecomment-614704835 and Git version...

**Comment by arthas168** [comment] 2020-09-16 06:21
@dominiksalvet git version is 2.28.0

I cleaned the gitpack cache and the issue is still there, I cannot find a `gitpack` file in my `~/.cache` folder though :(

**Comment by dominiksalvet** [comment] 2020-09-17 11:18
> I ran `gitpack clean` but the issue is still there, I cannot find a `gitpack` file in my `~/.cache` folder though :(

If you run `sudo gitpack ...` (global access), it uses `/var/cache/gitpack`. If you run `gitpack ...` (local access), it uses `~/.cache/gitpack`. E.g., try `sudo gitpack paths` vs `gitpack paths`...

> `gitpack.log` contains the following:

Are those the last lines after reaching the fatal error?

---

Anyway, please read https://github.com/dominiksalvet/gitpack/issues/7#issuecomment-614704835 again and answer all questions. Otherwise, I cannot help you.

I am also starting to suspect that you do not have the same issue as the OP. Please read all the issue posts again and let me know.

**Comment by dominiksalvet** [comment] 2021-01-23 17:41
Soon, the whole new GitPack, version 1.0.0, will be released and there is a [decent amount of changes](https://github.com/dominiksalvet/gitpack/blob/master/changelog.md) compared to 0.7.0. Closing this issue as it might be irrelevant for 1.0.0. Should it happen on 1.0.0 again, create a new issue or we can reopen this one. Thank you for understanding. :tada:

**Closed by dominiksalvet** 2021-01-23 17:41 UTC
Labels: bug
